### ISSUE TITLE
始终报 failure: ssl connection error: internal error (6)

### ISSUE THREAD

**Issue by cnwangfeng** [AlanLang/ros-ddns-serverless#1]
尊敬的作者，您好。
感谢开发这样的程序。

我测试中有如下问题，始终脚本无法正常运行上。我分别在ROS 7.6版本和ROS 6.49.7, X86版本上配置与运行。
错误提示如下。

[admin@MikroTik] /tool> /system script 
[admin@MikroTik] /system script> run script-aliyun-ddns 
failure: ssl connection error: internal error (6)
[admin@MikroTik] /system script> 

我如果把生成的URL粘出到浏览器运行，是成功的。但如果在RouterOS下，用/tool fetch运行就有这个问题。

**Comment by AlanLang** [comment]
vercel 被墙了，要科学上网才能访问。

**Comment by cnwangfeng** [comment]
呀。居然是这个原因。那关闭这个Issue吧。
