### ISSUE TITLE
vercel的部署以及获取url的问题

### ISSUE THREAD

**Issue by sinaamos** [AlanLang/ros-ddns-serverless#3]
请问vercel要怎么使用啊，我注册了账号，随便搞了下
我看vercel要从登录账号的github导入，所以我克隆了你的这个项目，然后vercel导入，vercel里所有选项全默认（因为不懂），然后部署，已经完成了，也不知道对不对，具体要怎么获得那个有解析结果的url？

**Comment by sinaamos** [comment]
出来了这3个，全部404，不知道什么意思
[ddns-sinaamos.vercel.app](https://ddns-sinaamos.vercel.app/)
[ddns-git-main-sinaamos.vercel.app](https://ddns-git-main-sinaamos.vercel.app/)
[ddns-three.vercel.app](https://ddns-three.vercel.app/)

**Comment by sinaamos** [comment]
出来了这3个，全部404，不知道什么意思
[ddns-sinaamos.vercel.app](https://ddns-sinaamos.vercel.app/)
[ddns-git-main-sinaamos.vercel.app](https://ddns-git-main-sinaamos.vercel.app/)
[ddns-three.vercel.app](https://ddns-three.vercel.app/)

**Comment by AlanLang** [comment]
https://ddns-sinaamos.vercel.app/api/aliyun
具体使用可以看 readme 里面链接的那篇文章：
https://alanlang.me/archives/ros%E8%B7%AF%E7%94%B1%E5%99%A8%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E8%AE%BE%E7%BD%AEddns

**Comment by sinaamos** [comment]
> https://ddns-sinaamos.vercel.app/api/aliyun 具体使用可以看 readme 里面链接的那篇文章： https://alanlang.me/archives/ros%E8%B7%AF%E7%94%B1%E5%99%A8%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E8%AE%BE%E7%BD%AEddns

作者你好，文章里主要是ros设置，ros里设置倒是没啥问题。主要我自己不是开发人员，完全不会vercel和github，毕竟也是为了ddns才去了解这个东西的。vercel就是能把github的项目直接部署起来？对于你的这个项目，直接导入部署，其他默认就行吧。

对于代码中的url部分只要把https://ros-ddns-serverless.vercel.app/api/aliyun替换成https://ddns-sinaamos.vercel.app/api/aliyun就行了吧。。。

**Comment by AlanLang** [comment]
> > https://ddns-sinaamos.vercel.app/api/aliyun 具体使用可以看 readme 里面链接的那篇文章： https://alanlang.me/archives/ros%E8%B7%AF%E7%94%B1%E5%99%A8%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E8%AE%BE%E7%BD%AEddns
> 
> 作者你好，文章里主要是ros设置，ros里设置倒是没啥问题。主要我自己不是开发人员，完全不会vercel和github，毕竟也是为了ddns才去了解这个东西的。vercel就是能把github的项目直接部署起来？对于你的这个项目，直接导入部署，其他默认就行吧。
> 
> 对于代码中的url部分只要把[https://ros-ddns-serverless.vercel.app/api/aliyun替换成https://ddns-sinaamos.vercel.app/api/aliyun就行了吧。。。](https://ros-ddns-serverless.vercel.app/api/aliyun%E6%9B%BF%E6%8D%A2%E6%88%90https://ddns-sinaamos.vercel.app/api/aliyun%E5%B0%B1%E8%A1%8C%E4%BA%86%E5%90%A7%E3%80%82%E3%80%82%E3%80%82)

是的，不过要注意，vercel 现在被墙了，如果 ros 没有翻墙可能访问不到。
我现在已经不使用这个方案了，而是在 ros 里直接调用 Cloudflare ddns 的接口了。
